coverage:
  status:
    project:
      default:
        # basic
        target: 0%
        threshold: 10%
        # advanced settings
        branches:
          - master
          - dev
          - feature/projects
        if_ci_failed: error #success, failure, error, ignore
        informational: true
        only_pulls: false
    patch:
      default:
        informational: true
comment: false
